frameworkVersion: '3'
service: vanilla-template

provider:
  name: aws
  runtime: python3.9

functions:
  app:
    handler: app.main.seda
    seda: true

plugins:
  - serverless-seda
  - serverless-python-requirements
  - serverless-offline

package:
  patterns:
    - '!.env'
    - '!.*_cache/**'
    - '!app/tests/**'
    - '!node_modules/**'
    - '!venv/**'
